<?php

use Drupal\rdfui\ContentMappings;

function rdfui_menu() {
    $items['rdfui']=array(
        'title' => 'Schema Mapping',
        'route_name'=>'rdfui.mappinglisting'
    );

    $items['/admin/config/types']=array(
        'title'=>'List all Content types',
        'route_name'=>'rdfui.overview_types',
    );


    return  $items;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function rdfui_form_node_type_add_form_alter(&$form, &$form_state,$form_id){
    $form+=ContentMappings::alter_form($form,$form_state);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function rdfui_form_node_type_edit_form_alter(&$form, &$form_state,$form_id){
    $form+=ContentMappings::alter_form($form,$form_state);
}
