<?php
/**
 * @file
 * The module that allows content types and fields to be mapped with
 * rdf data from Schema.org.
 */

use Drupal\rdfui\ContentMappings;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function rdfui_form_node_type_add_form_alter(&$form, &$form_state) {
  $form += ContentMappings::alter_form($form, $form_state);
  //$form['actions']['save_continue']['#validate'][] = <method>;
  $form['actions']['submit']['#submit'][] = 'rdfui_node_type_form_submit';
  $form['actions']['save_continue']['#submit'][] = 'rdfui_node_type_form_submit';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function rdfui_form_node_type_edit_form_alter(&$form, &$form_state, $form_id) {
  $form += ContentMappings::alter_form($form, $form_state);
  //$form['actions']['submit']['#validate'][] = <method>;
  $form['actions']['submit']['#submit'][] = 'rdfui_node_type_form_submit';
}

function rdfui_node_type_form_submit(&$form, &$form_state) {
  ContentMappings::submitForm($form, $form_state);
}
